version: '3.8'

services:
  creni:
    build: .
    container_name: ai
    volumes:
      - ./INPUT:/app/INPUT  
      - ./OUTPUT:/app/OUTPUT
    working_dir: /app
    restart: always
    tty: true
    # environment:
    #   - ENV=/opt/venv
    #   - PATH=/opt/venv/bin:$PATH
